### ISSUE TITLE
Name collision with JavaScriptCore

### ISSUE THREAD

**Issue by geoff-nixon** [eatonphil/jsc#28]
Hey, cool project! So I thought I'd just give you a heads up if you weren't already aware that `jsc` is (and has always been extensively used as the name for the compiler/interpreter/assembler in Apple's JavaScriptCore library, which is fairly ubiquitous since it's used in Safari and it is the only JS engine allowed on iOS. I'm not trying to be melodramatic, but in all seriousness, there's an executable distributed with the library (usually at `JavaScriptCore.framework/Versions/A/Helpers/jsc` which is effectively a drop-in for calling the `node` executable (or what have you):

```
Usage: jsc [options] [files] [-- arguments]
  -d         Dumps bytecode (debug builds only)
  -e         Evaluate argument as script code
  -f         Specifies a source file (deprecated)
  -h|--help  Prints this help message
  -i         Enables interactive mode (default if no files are specified)
  -m         Execute as a module
  -s         Installs signal handlers that exit on a crash (Unix platforms only)
  -p <file>  Outputs profiling data to a file
  -x         Output exit code before terminating
  --sample                   Collects and outputs sampling profiler data
  --test262-async            Check that some script calls the print function with the string 'Test262:AsyncTestComplete'
  --strict-file=<file>       Parse the given file as if it were in strict mode (this option may be passed more than once)
  --module-file=<file>       Parse and evaluate the given file as module (this option may be passed more than once)
  --exception=<name>         Check the last script exits with an uncaught exception with the specified name
  --watchdog-exception-ok    Uncaught watchdog exceptions exit with success
  --dumpException            Dump uncaught exception text
  --footprint                Dump memory footprint after done executing
  --options                  Dumps all JSC VM options and exits
  --dumpOptions              Dumps all non-default JSC VM options before continuing
  --<jsc VM option>=<value>  Sets the specified JSC VM option
  --destroy-vm               Destroy VM before exiting
Files with a .mjs extension will always be evaluated as modules.
```  

Additionally, the JavaScriptCore source uses "JSC" as well almost exclusively, like `to JSC::JSObject::putDirectIndex(JSC::JSGlobalObject *, unsigned int, JSC::JSValue, unsigned int, JSC::PutDirectIndexMode)`.

So, just a thought, you may want to rename while still in development if you don't want to clash with Apple down the road.

Cheers,

Geoff

**Comment by rauschma** [comment]
Yes, please rename! The current name really confused me (due to what @geoff-nixon explained).

**Comment by eatonphil** [comment]
Thanks folks, I'm not interested in renaming this repo at this time. I'm sure it will not be hard to figure out the difference between this project and JavaScript Core. There's also no conflict with the JSC namespace (`git grep JSC` returns nothing; though I can't imagine why anyone would be importing both this project and JavaScript Core code).
