### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by prashast** [eatonphil/jsc#30]
Hi, thanks for creating this project! Could you please clarify the build instructions for `jsc`. I have installed both `yarn` and `node` and they're on my `PATH`. However, when I try to run `yarn` inside the `jsc` folder, it just gives me the message: `ERROR: There are no scenarios; must have at least one`. I tried running `yarn tsc` as well but then it gave me the error: `ERROR: No such file or directory 'run'`. 

Could you let me know the set of commands I need to run to setup the `jsc` compiler?

**Comment by eatonphil** [comment]
There is a CircleCI build that runs on every commit and it is passing ([details here](https://github.com/eatonphil/jsc/blob/master/.circleci/config.yml)).

The error `There are no scenarios` sounds like you either don't have the source or you aren't calling `yarn` within this directory. It is a pretty generic yarn error.

There is no reference to a `run` directory either so it sounds like you're just running these commands in a different directory.

If this issue persists and you think I'm mistaken feel free to re-open with more detail.
